require("settings")
require("maps")
require("plugins")
vim.cmd("set ls=3")
vim.cmd("colorscheme nightfox")
vim.cmd("set fillchars=eob:\\ ")
vim.cmd([[highlight Normal guibg=#00101f]])
vim.cmd([[highlight NormalFloat guibg=#00101f]])
vim.cmd([[highlight WinSeparator guifg=#2e4158]])
vim.cmd([[autocmd User TelescopePreviewerLoaded setlocal number]])
